server:
  port: 8084
spring:
  application:
    name: page-server
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.56.110
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
